# Evershop + PostgreSQL Kubernetes stack
# Save this file as evershop-k8s.yaml and apply with:
#   kubectl apply -f evershop-k8s.yaml
# It contains:
#   * PersistentVolumeClaim for PostgreSQL data
#   * Deployment & Service for PostgreSQL (named "database")
#   * Deployment & Service for Evershop app
# Adjust storage class, resource limits, or Service types as needed.

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # change size as required
  storageClassName: standard  # adjust or remove if default class is desired

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "postgres"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evershop-app
  labels:
    app: evershop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evershop
  template:
    metadata:
      labels:
        app: evershop
    spec:
      containers:
        - name: evershop
          image: evershop/evershop:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "database"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "postgres"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: evershop-service
  labels:
    app: evershop
spec:
  type: NodePort  # use LoadBalancer on cloud for external endpoint
  selector:
    app: evershop
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30000  # optional static port, else remove this line

# now try it by :
#  kubectl port-forward svc/evershop-service 3000:3000