apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: evershop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<your-username>/evershop-gitops
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
